# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MS2_CSort_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1263, 725)
        MainWindow.setMinimumSize(QtCore.QSize(1263, 725))
        MainWindow.setMaximumSize(QtCore.QSize(1263, 725))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(400, 40, 71, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(170, 70, 61, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(70, 40, 321, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setMaxLength(1000000000)
        self.lineEdit.setObjectName("lineEdit")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(20, 100, 451, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 40, 54, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(250, 70, 61, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(720, 10, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(500, 10, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(630, 40, 191, 20))
        self.horizontalSlider.setMaximum(100000)
        self.horizontalSlider.setSingleStep(1)
        self.horizontalSlider.setPageStep(1)
        self.horizontalSlider.setProperty("value", 92000)
        self.horizontalSlider.setSliderPosition(92000)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(500, 70, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(720, 70, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(630, 100, 191, 20))
        self.horizontalSlider_2.setMaximum(100000)
        self.horizontalSlider_2.setPageStep(1)
        self.horizontalSlider_2.setProperty("value", 8000)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(500, 130, 321, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.start.setFont(font)
        self.start.setObjectName("start")
        self.Positive = QtWidgets.QLabel(self.centralwidget)
        self.Positive.setGeometry(QtCore.QRect(910, 10, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Positive.setFont(font)
        self.Positive.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Positive.setObjectName("Positive")
        self.Fuzzy = QtWidgets.QLabel(self.centralwidget)
        self.Fuzzy.setGeometry(QtCore.QRect(1000, 10, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Fuzzy.setFont(font)
        self.Fuzzy.setObjectName("Fuzzy")
        self.Negative = QtWidgets.QLabel(self.centralwidget)
        self.Negative.setGeometry(QtCore.QRect(1090, 10, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Negative.setFont(font)
        self.Negative.setObjectName("Negative")
        self.All = QtWidgets.QLabel(self.centralwidget)
        self.All.setGeometry(QtCore.QRect(1180, 10, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.All.setFont(font)
        self.All.setObjectName("All")
        self.Num = QtWidgets.QLabel(self.centralwidget)
        self.Num.setGeometry(QtCore.QRect(840, 51, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Num.setFont(font)
        self.Num.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Num.setObjectName("Num")
        self.Ratio = QtWidgets.QLabel(self.centralwidget)
        self.Ratio.setGeometry(QtCore.QRect(840, 91, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Ratio.setFont(font)
        self.Ratio.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Ratio.setObjectName("Ratio")
        self.AllRatio = QtWidgets.QTextBrowser(self.centralwidget)
        self.AllRatio.setGeometry(QtCore.QRect(1180, 90, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.AllRatio.setFont(font)
        self.AllRatio.setObjectName("AllRatio")
        self.NegativeRatio = QtWidgets.QTextBrowser(self.centralwidget)
        self.NegativeRatio.setGeometry(QtCore.QRect(1090, 90, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.NegativeRatio.setFont(font)
        self.NegativeRatio.setObjectName("NegativeRatio")
        self.NegativeNum = QtWidgets.QTextBrowser(self.centralwidget)
        self.NegativeNum.setGeometry(QtCore.QRect(1090, 50, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.NegativeNum.setFont(font)
        self.NegativeNum.setObjectName("NegativeNum")
        self.AllNum = QtWidgets.QTextBrowser(self.centralwidget)
        self.AllNum.setGeometry(QtCore.QRect(1180, 50, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.AllNum.setFont(font)
        self.AllNum.setObjectName("AllNum")
        self.FuzzyNum = QtWidgets.QTextBrowser(self.centralwidget)
        self.FuzzyNum.setGeometry(QtCore.QRect(1000, 50, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.FuzzyNum.setFont(font)
        self.FuzzyNum.setObjectName("FuzzyNum")
        self.FuzzyRatio = QtWidgets.QTextBrowser(self.centralwidget)
        self.FuzzyRatio.setGeometry(QtCore.QRect(1000, 90, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.FuzzyRatio.setFont(font)
        self.FuzzyRatio.setObjectName("FuzzyRatio")
        self.PositiveNum = QtWidgets.QTextBrowser(self.centralwidget)
        self.PositiveNum.setGeometry(QtCore.QRect(910, 50, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PositiveNum.setFont(font)
        self.PositiveNum.setObjectName("PositiveNum")
        self.PositiveRatio = QtWidgets.QTextBrowser(self.centralwidget)
        self.PositiveRatio.setGeometry(QtCore.QRect(910, 90, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PositiveRatio.setFont(font)
        self.PositiveRatio.setObjectName("PositiveRatio")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.OutputDirectoryLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.OutputDirectoryLineEdit.setGeometry(QtCore.QRect(70, 10, 321, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.OutputDirectoryLineEdit.setFont(font)
        self.OutputDirectoryLineEdit.setObjectName("OutputDirectoryLineEdit")
        self.OutputBrowse = QtWidgets.QPushButton(self.centralwidget)
        self.OutputBrowse.setGeometry(QtCore.QRect(400, 10, 71, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.OutputBrowse.setFont(font)
        self.OutputBrowse.setObjectName("OutputBrowse")
        self.Save = QtWidgets.QPushButton(self.centralwidget)
        self.Save.setGeometry(QtCore.QRect(840, 130, 411, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Save.setFont(font)
        self.Save.setObjectName("Save")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(110, 200, 281, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setMaxLength(1000000000)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(400, 200, 71, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 200, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(400, 230, 71, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(110, 230, 281, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setMaxLength(1000000000)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 230, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(400, 260, 71, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(110, 260, 281, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setMaxLength(1000000000)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 260, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.listWidget_2 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_2.setGeometry(QtCore.QRect(20, 320, 451, 311))
        self.listWidget_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.listWidget_2.setFont(font)
        self.listWidget_2.setObjectName("listWidget_2")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(20, 640, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(500, 160, 751, 471))
        self.graphicsView.setObjectName("graphicsView")
        self.Save_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Save_2.setGeometry(QtCore.QRect(500, 640, 751, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Save_2.setFont(font)
        self.Save_2.setObjectName("Save_2")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(180, 290, 291, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(479, -10, 16, 791))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(110, 290, 61, 22))
        self.spinBox.setMinimum(50)
        self.spinBox.setMaximum(500)
        self.spinBox.setProperty("value", 150)
        self.spinBox.setObjectName("spinBox")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 290, 91, 20))
        self.label_8.setObjectName("label_8")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(820, 0, 20, 151))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1263, 23))
        self.menubar.setObjectName("menubar")
        self.menuMs_classification = QtWidgets.QMenu(self.menubar)
        self.menuMs_classification.setObjectName("menuMs_classification")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuMs_classification.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Browse"))
        self.pushButton_2.setText(_translate("MainWindow", "Add"))
        self.label.setText(_translate("MainWindow", "mzXML:"))
        self.pushButton_3.setText(_translate("MainWindow", "Remove"))
        self.lineEdit_2.setText(_translate("MainWindow", "0.92"))
        self.label_2.setText(_translate("MainWindow", "Upper threshold:"))
        self.label_3.setText(_translate("MainWindow", "Lower threshold:"))
        self.lineEdit_3.setText(_translate("MainWindow", "0.08"))
        self.start.setText(_translate("MainWindow", "Start"))
        self.Positive.setText(_translate("MainWindow", "Positive"))
        self.Fuzzy.setText(_translate("MainWindow", "Fuzzy"))
        self.Negative.setText(_translate("MainWindow", "Negative"))
        self.All.setText(_translate("MainWindow", "All"))
        self.Num.setText(_translate("MainWindow", "Number"))
        self.Ratio.setText(_translate("MainWindow", "Ratio"))
        self.label_4.setText(_translate("MainWindow", "Output:"))
        self.OutputBrowse.setText(_translate("MainWindow", "Browse"))
        self.Save.setText(_translate("MainWindow", "Save"))
        self.pushButton_4.setText(_translate("MainWindow", "Browse"))
        self.label_5.setText(_translate("MainWindow", "aligned.tsv:"))
        self.pushButton_5.setText(_translate("MainWindow", "Browse"))
        self.label_6.setText(_translate("MainWindow", "lib.os.tsv:"))
        self.pushButton_6.setText(_translate("MainWindow", "Browse"))
        self.label_7.setText(_translate("MainWindow", "win.os.tsv:"))
        self.pushButton_7.setText(_translate("MainWindow", "Plot"))
        self.Save_2.setText(_translate("MainWindow", "Save figure"))
        self.pushButton_8.setText(_translate("MainWindow", "Run to extract ion chromatogram"))
        self.label_8.setText(_translate("MainWindow", "Length of XIC:"))
        self.menuMs_classification.setTitle(_translate("MainWindow", "MSSort-DIA-XMBD"))

